CREATE TABLE AUTHOR(
	AUTHOR_ID INT PRIMARY KEY,
	AUTHOR_NAME VARCHAR(20),
	COUNTRY VARCHAR(20)
)

CREATE TABLE BOOK (
	BOOK_ID INT PRIMARY KEY,
	BOOK_TITLE VARCHAR(20),
	AUTHOR_ID INT  /* It is not necessary to keep the column name of foreign key and primary key same.*/
	FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID)
)

INSERT INTO AUTHOR
VALUES
(1,'A', 'INDIA'),
(2,'B', 'USA'),
(3,'C', 'INDIA'),
(4,'D', 'AUSTRALIA');

INSERT INTO BOOK
VALUES
(101,'AB', 2),
(102,'BC', 1),
(103,'CD', 3),
(104,'DE', 4);

SELECT A.AUTHOR_NAME, A.COUNTRY , B.BOOK_TITLE
FROM AUTHOR  AS A
INNER JOIN
BOOK  AS B
ON 
A.AUTHOR_ID = B.AUTHOR_ID